import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, CalendarDays, CheckCircle2, Clock3, ExternalLink, MessageSquareText, Plus, Save, ShieldCheck, Smartphone, Trash2, UserCheck, UsersRound } from 'lucide-react';
import { api } from '../../api/client';
import BiometricEnrollmentManager from '../../components/Setup/BiometricEnrollmentManager';

const tabs = [['operations', 'Attendance rules'], ['biometrics', 'Face enrollments'], ['sms', 'Android SMS'], ['privacy', 'Privacy & legal setup'], ['access', 'Roles & corrections']];
const defaultSms = {
  enabled: false, gateway_url: 'http://192.168.1.100:8080', username: '', password: '', school_contact: 'the school office',
  templates: {
    time_in: 'EduScan: {name} entered San Jose National High School at {time} on {date}. If unexpected, contact {school_contact}.',
    time_out: 'EduScan: {name} left San Jose National High School at {time} on {date}. If unexpected, contact {school_contact}.',
    tardiness: 'EduScan: {name} arrived at {time} on {date} and was marked late for {class_name} (start: {class_start}). Contact {school_contact} for corrections.',
    absence: 'EduScan: No time-in was recorded for {name} by {absence_cutoff} on {date}; the learner was marked absent pending teacher review. Contact {school_contact}.',
  },
};
const complianceFields = [
  ['school_approval_reference', 'School approval reference'], ['parent_consent_process_reference', 'Parent/minor consent process'],
  ['dpo_pia_reference', 'DPO-approved Privacy Impact Assessment'], ['sdo_deped_clearance_reference', 'Schools Division Office / DepEd determination'],
  ['ai_registry_reference', 'Required AI system inventory/registry entry'], ['records_schedule_reference', 'Approved records retention/disposition schedule'],
  ['acceptable_use_policy_reference', 'Acceptable-use and staff procedure'], ['breach_response_reference', 'Breach and incident response plan'],
];

export default function SystemSetup() {
  const [active, setActive] = useState('operations');
  const [settings, setSettings] = useState({ attendance: { absence_cutoff: '09:00', duplicate_cooldown_seconds: 45, auto_close_enabled: true }, sms: defaultSms, compliance: {} });
  const [schedules, setSchedules] = useState([]);
  const [outbox, setOutbox] = useState([]);
  const [biometric, setBiometric] = useState(null);
  const [notice, setNotice] = useState('');
  const [error, setError] = useState('');
  const [newSchedule, setNewSchedule] = useState({ grade: '10', section: 'Rizal', subject: '', teacher_name: '', weekdays: '0,1,2,3,4', start_time: '07:30', end_time: '08:30', late_grace_minutes: 15, active: true });
  const [testPhone, setTestPhone] = useState('');
  const [calendarRows, setCalendarRows] = useState([]);
  const [excusedRows, setExcusedRows] = useState([]);
  const [people, setPeople] = useState([]);
  const [calendarForm, setCalendarForm] = useState({ event_date: new Date().toISOString().slice(0, 10), event_type: 'Holiday', reason: '', start_time: '', end_time: '', absence_cutoff: '' });
  const [excusedForm, setExcusedForm] = useState({ person_id: '', event_date: new Date().toISOString().slice(0, 10), reason: '' });

  const load = useCallback(async () => {
    try {
      const [config, scheduleRows, smsRows, biometricStatus, calendarData, excusedData, personRows] = await Promise.all([api.get('/settings'), api.get('/schedules'), api.get('/sms/outbox'), api.get('/biometrics/status'), api.get('/calendar/exceptions'), api.get('/attendance/excused'), api.get('/persons')]);
      setSettings({ ...config, sms: { ...defaultSms, ...config.sms, templates: { ...defaultSms.templates, ...(config.sms?.templates || {}) } } });
      setSchedules(scheduleRows); setOutbox(smsRows); setBiometric(biometricStatus);
      setCalendarRows(calendarData); setExcusedRows(excusedData); setPeople(personRows);
    } catch (err) { setError(err.message); }
  }, []);
  useEffect(() => { load(); }, [load]);
  const success = (message) => { setNotice(message); setError(''); window.setTimeout(() => setNotice(''), 3500); };
  const patchArea = (area, field, value) => setSettings((current) => ({ ...current, [area]: { ...current[area], [field]: value } }));

  const saveAttendance = async () => { try { await api.put('/settings/attendance', settings.attendance); success('Attendance rules saved to the database.'); } catch (err) { setError(err.message); } };
  const saveSms = async () => { try { const s = settings.sms; await api.put('/settings/sms', { enabled: s.enabled, gateway_url: s.gateway_url, username: s.username, password: s.password || null, school_contact: s.school_contact, time_in_template: s.templates.time_in, time_out_template: s.templates.time_out, tardiness_template: s.templates.tardiness, absence_template: s.templates.absence }); success('Android gateway credentials and message templates saved; password stored encrypted.'); await load(); } catch (err) { setError(err.message); } };
  const saveCompliance = async () => { try { await api.put('/settings/compliance', Object.fromEntries(complianceFields.map(([key]) => [key, settings.compliance[key] || '']))); success('Deployment evidence references saved.'); } catch (err) { setError(err.message); } };
  const addSchedule = async () => { if (!newSchedule.subject || !newSchedule.teacher_name) return setError('Subject and teacher are required.'); try { await api.post('/schedules', newSchedule); success('Class schedule saved.'); setNewSchedule((current) => ({ ...current, subject: '', teacher_name: '' })); await load(); } catch (err) { setError(err.message); } };
  const removeSchedule = async (id) => { try { await api.delete(`/schedules/${id}`); await load(); } catch (err) { setError(err.message); } };
  const sendTest = async () => { const form = new FormData(); form.append('phone', testPhone); form.append('message', 'EduScan Android gateway connection test from San Jose National High School.'); try { const result = await api.post('/sms/test', form); if (result.status === 'sent') success('Test SMS accepted by the Android gateway.'); else setError(result.error || `Test status: ${result.status}`); await load(); } catch (err) { setError(err.message); } };
  const saveCalendar = async () => { try { await api.post('/calendar/exceptions', { ...calendarForm, start_time: calendarForm.start_time || null, end_time: calendarForm.end_time || null, absence_cutoff: calendarForm.absence_cutoff || null }); success('Calendar exception saved.'); setCalendarForm((current) => ({ ...current, reason: '' })); await load(); } catch (err) { setError(err.message); } };
  const removeCalendar = async (id) => { try { await api.delete(`/calendar/exceptions/${id}`); await load(); } catch (err) { setError(err.message); } };
  const saveExcused = async () => { if (!excusedForm.person_id) return setError('Select a person for the excused absence.'); try { await api.post('/attendance/excused', { ...excusedForm, person_id: Number(excusedForm.person_id) }); success('Excused absence recorded.'); setExcusedForm((current) => ({ ...current, reason: '' })); await load(); } catch (err) { setError(err.message); } };
  const removeExcused = async (id) => { try { await api.delete(`/attendance/excused/${id}`); await load(); } catch (err) { setError(err.message); } };

  return <div className="page-stack">
    <div className="page-heading"><div><p className="eyebrow">Operational configuration</p><h1>System setup & governance</h1><p>Configure the working attendance, LBPH, Android SMS, reporting, access, and deployment evidence controls.</p></div></div>
    {notice && <div className="notice notice-success"><CheckCircle2 size={18} /> {notice}</div>}{error && <div className="notice notice-danger"><AlertTriangle size={18} /> {error}</div>}
    <div className="notice notice-blue"><ShieldCheck size={19} /><div><strong>LBPH runtime: {biometric?.enabled ? 'enabled' : 'server-disabled'}.</strong> {biometric?.model ? `Active model ${biometric.model.version}: ${biometric.model.person_count} enrolled person(s), ${biometric.model.sample_count} samples.` : 'No trained model yet. Enroll an authorized person from the gate station.'} Deployment evidence below does not switch off development operation; it records the approvals required before live school use.</div></div>
    <div className="setup-tabs">{tabs.map(([id, label]) => <button key={id} className={active === id ? 'active' : ''} onClick={() => setActive(id)}>{label}</button>)}</div>

    {active === 'operations' && <div className="page-stack">
      <section className="card-static"><div className="section-heading"><div><p className="eyebrow">Automated classification defaults</p><h2>Attendance rules</h2></div><Clock3 size={24} /></div><p className="section-copy">Accepted matches alternate between time-in and time-out, supporting multiple exits and re-entries. Schedule-specific grace periods determine the first arrival’s tardiness.</p><div className="form-grid two-columns"><label><span className="field-label">Authorized absence cutoff</span><input className="input-field" type="time" value={settings.attendance.absence_cutoff} onChange={(e) => patchArea('attendance', 'absence_cutoff', e.target.value)} /></label><label><span className="field-label">Duplicate scan cooldown (seconds)</span><input className="input-field" type="number" min="5" value={settings.attendance.duplicate_cooldown_seconds} onChange={(e) => patchArea('attendance', 'duplicate_cooldown_seconds', Number(e.target.value))} /></label><label className="checkbox-field"><input type="checkbox" checked={settings.attendance.auto_close_enabled} onChange={(e) => patchArea('attendance', 'auto_close_enabled', e.target.checked)} /><span>Automatically close attendance and queue absence notices at the cutoff</span></label></div><div className="modal-actions"><button className="btn-primary" onClick={saveAttendance}><Save size={16} /> Save rules</button></div></section>
      <section className="card-static"><div className="section-heading"><div><p className="eyebrow">Teacher-defined schedules</p><h2>Class schedules</h2></div><Plus size={24} /></div><div className="table-scroll"><table className="interactive-table"><thead><tr><th>Grade & section</th><th>Subject</th><th>Teacher</th><th>Weekdays</th><th>Time</th><th>Grace</th><th /></tr></thead><tbody>{schedules.map((item) => <tr key={item.id}><td>{item.grade} — {item.section}</td><td>{item.subject}</td><td>{item.teacher_name}</td><td>{item.weekdays}</td><td>{item.start_time}–{item.end_time}</td><td>{item.late_grace_minutes} min</td><td><button className="btn-link danger-link" onClick={() => removeSchedule(item.id)}><Trash2 size={15} /> Remove</button></td></tr>)}</tbody></table></div><div className="inline-editor">{[['grade', 'Grade'], ['section', 'Section'], ['subject', 'Subject'], ['teacher_name', 'Teacher'], ['weekdays', 'Weekdays 0–6'], ['start_time', 'Start'], ['end_time', 'End']].map(([field, label]) => <label key={field}><span className="field-label">{label}</span><input className="input-field" type={field.includes('time') ? 'time' : 'text'} value={newSchedule[field]} onChange={(e) => setNewSchedule((current) => ({ ...current, [field]: e.target.value }))} /></label>)}<button className="btn-secondary" onClick={addSchedule}><Plus size={16} /> Add</button></div></section>
      <section className="card-static"><div className="section-heading"><div><p className="eyebrow">Non-instructional and adjusted days</p><h2>School calendar exceptions</h2></div><CalendarDays size={24} /></div><div className="form-grid three-columns"><label><span className="field-label">Date</span><input className="input-field" type="date" value={calendarForm.event_date} onChange={(e) => setCalendarForm((current) => ({ ...current, event_date: e.target.value }))} /></label><label><span className="field-label">Type</span><select className="input-field" value={calendarForm.event_type} onChange={(e) => setCalendarForm((current) => ({ ...current, event_type: e.target.value }))}><option>Holiday</option><option>Suspended</option><option>Special Schedule</option></select></label><label><span className="field-label">Reason / authority</span><input className="input-field" value={calendarForm.reason} onChange={(e) => setCalendarForm((current) => ({ ...current, reason: e.target.value }))} /></label>{calendarForm.event_type === 'Special Schedule' && <><label><span className="field-label">Start</span><input className="input-field" type="time" value={calendarForm.start_time} onChange={(e) => setCalendarForm((current) => ({ ...current, start_time: e.target.value }))} /></label><label><span className="field-label">End</span><input className="input-field" type="time" value={calendarForm.end_time} onChange={(e) => setCalendarForm((current) => ({ ...current, end_time: e.target.value }))} /></label><label><span className="field-label">Absence cutoff</span><input className="input-field" type="time" value={calendarForm.absence_cutoff} onChange={(e) => setCalendarForm((current) => ({ ...current, absence_cutoff: e.target.value }))} /></label></>}</div><div className="modal-actions"><button className="btn-primary" onClick={saveCalendar}><Plus size={16} /> Save calendar day</button></div><div className="table-scroll"><table className="interactive-table"><thead><tr><th>Date</th><th>Type</th><th>Reason</th><th>Special times</th><th /></tr></thead><tbody>{calendarRows.map((item) => <tr key={item.id}><td>{item.event_date}</td><td>{item.event_type}</td><td>{item.reason}</td><td>{item.start_time ? `${item.start_time}–${item.end_time || '—'} · cutoff ${item.absence_cutoff || 'default'}` : '—'}</td><td><button className="btn-link danger-link" onClick={() => removeCalendar(item.id)}><Trash2 size={14} /> Remove</button></td></tr>)}</tbody></table></div></section>
      <section className="card-static"><div className="section-heading"><div><p className="eyebrow">Authorized learner exception</p><h2>Excused absences</h2></div><UserCheck size={24} /></div><div className="form-grid three-columns"><label><span className="field-label">Person</span><select className="input-field" value={excusedForm.person_id} onChange={(e) => setExcusedForm((current) => ({ ...current, person_id: e.target.value }))}><option value="">Select</option>{people.map((item) => <option key={item.id} value={item.id}>{item.full_name} · {item.external_id}</option>)}</select></label><label><span className="field-label">Date</span><input className="input-field" type="date" value={excusedForm.event_date} onChange={(e) => setExcusedForm((current) => ({ ...current, event_date: e.target.value }))} /></label><label><span className="field-label">Reason / supporting reference</span><input className="input-field" value={excusedForm.reason} onChange={(e) => setExcusedForm((current) => ({ ...current, reason: e.target.value }))} /></label></div><div className="modal-actions"><button className="btn-primary" onClick={saveExcused}><Plus size={16} /> Record excuse</button></div><div className="table-scroll"><table className="interactive-table"><thead><tr><th>Date</th><th>Person</th><th>Reason</th><th>Actor</th><th /></tr></thead><tbody>{excusedRows.map((item) => <tr key={item.id}><td>{item.event_date}</td><td>{item.person_name}</td><td>{item.reason}</td><td>{item.actor_name}</td><td><button className="btn-link danger-link" onClick={() => removeExcused(item.id)}><Trash2 size={14} /> Remove</button></td></tr>)}</tbody></table></div></section>
    </div>}

    {active === 'biometrics' && <BiometricEnrollmentManager onModelChanged={load} />}

    {active === 'sms' && <div className="page-stack">
      <section className="card-static"><div className="section-heading"><div><p className="eyebrow">Real local relay</p><h2>Android SMS Gateway</h2></div><Smartphone size={26} /></div><ol className="numbered-list"><li>Install SMS Gateway for Android on a dedicated phone with a school-controlled SIM.</li><li>Place the phone and EduScan server on the same secured Wi-Fi; reserve the phone’s IP address.</li><li>In the app, enable Local Server mode and create a strong username/password.</li><li>Enter the local URL and credentials below. The backend posts to /message with HTTP Basic authentication.</li><li>Keep the phone charged, exempt the app from battery optimization, restrict the endpoint to the school LAN, and monitor failed messages.</li></ol><div className="form-grid two-columns"><label className="checkbox-field"><input type="checkbox" checked={settings.sms.enabled} onChange={(e) => patchArea('sms', 'enabled', e.target.checked)} /><span>Enable real Android gateway dispatch</span></label><label><span className="field-label">Gateway URL</span><input className="input-field" value={settings.sms.gateway_url} onChange={(e) => patchArea('sms', 'gateway_url', e.target.value)} /></label><label><span className="field-label">API username</span><input className="input-field" value={settings.sms.username} onChange={(e) => patchArea('sms', 'username', e.target.value)} /></label><label><span className="field-label">API password {settings.sms.password_configured && '(leave blank to keep current)'}</span><input className="input-field" type="password" value={settings.sms.password} onChange={(e) => patchArea('sms', 'password', e.target.value)} /></label><label><span className="field-label">School contact shown in SMS</span><input className="input-field" value={settings.sms.school_contact} onChange={(e) => patchArea('sms', 'school_contact', e.target.value)} /></label></div></section>
      <section className="card-static"><h2>Approved message templates</h2><div className="template-grid">{Object.entries(settings.sms.templates).map(([key, value]) => <label key={key}><span className="field-label">{key.replace('_', ' ')}</span><textarea className="text-area" value={value} onChange={(e) => setSettings((current) => ({ ...current, sms: { ...current.sms, templates: { ...current.sms.templates, [key]: e.target.value } } }))} /><span className="token-help">Use: {'{name} {time} {date} {class_name} {class_start} {absence_cutoff} {school_contact}'}</span></label>)}</div><div className="modal-actions"><button className="btn-primary" onClick={saveSms}><Save size={16} /> Save gateway & templates</button></div></section>
      <section className="card-static"><h2>Connection test and delivery outbox</h2><div className="action-row"><input className="input-field" placeholder="+639XXXXXXXXX" value={testPhone} onChange={(e) => setTestPhone(e.target.value)} /><button className="btn-secondary" onClick={sendTest}><MessageSquareText size={16} /> Send real test SMS</button></div><div className="table-scroll"><table className="interactive-table"><thead><tr><th>Created</th><th>Event</th><th>Recipient</th><th>Message</th><th>Status</th><th>Error</th></tr></thead><tbody>{outbox.length === 0 && <tr><td colSpan="6" className="empty-cell">No messages queued.</td></tr>}{outbox.map((item) => <tr key={item.id}><td>{new Date(item.created_at).toLocaleString('en-PH')}</td><td>{item.event_type}</td><td>{item.recipient}</td><td className="message-cell">{item.message}</td><td>{item.status}</td><td>{item.last_error || '—'}</td></tr>)}</tbody></table></div></section>
    </div>}

    {active === 'privacy' && <PrivacyLegal settings={settings} setSettings={setSettings} saveCompliance={saveCompliance} />}
    {active === 'access' && <AccessControls />}
  </div>;
}

function PrivacyLegal({ settings, setSettings, saveCompliance }) {
  return <div className="page-stack">
    <section className="card-static privacy-notice"><div className="section-heading"><div><p className="eyebrow">Privacy notice for final DPO approval</p><h2>EduScan data processing notice</h2></div><ShieldCheck size={26} /></div><p><strong>Controller:</strong> San Jose National High School through its authorized officials and designated Data Protection Officer. Add the DPO contact before collection.</p><p><strong>Data and purpose:</strong> identity, role/class, sex for SF2 placement, guardian contact, attendance, corrections, grades, audit data, encrypted enrollment images, and LBPH templates are processed only for attendance, notices, grading, official reporting, security, correction, and accountability.</p><p><strong>Automated process:</strong> a local camera extracts every detectable face crop in a frame; LBPH compares each distinct face with authorized enrollment samples. Verified matches alternate between time-in and time-out throughout the day, while schedules and calendar rules propose tardy or absent status. Staff can review and correct records. Do not use automated matching as the sole basis for discipline.</p><p><strong>Sharing and rights:</strong> restrict data to authorized school personnel and contracted processors. Data subjects may request information, access, correction, restriction/erasure where applicable, object where applicable, and lodge a complaint with the DPO/NPC.</p><p><strong>Safeguards:</strong> local processing, encrypted biometric files, password-protected roles, TLS for deployed access, full-disk encryption, secured kiosk, immutable raw events, audit logs, encrypted backups, breach response, staff training, and authorized secure deletion.</p></section>
    <section className="card-static"><div className="section-heading"><div><p className="eyebrow">Required before live deployment</p><h2>Approval and evidence register</h2></div><Save size={24} /></div><div className="notice notice-warning"><AlertTriangle size={18} /> These references document compliance work; entering text is not itself legal approval. Retention periods must follow the final DepEd/National Archives schedule approved by the school records officer and DPO.</div><div className="form-grid two-columns">{complianceFields.map(([key, label]) => <label key={key}><span className="field-label">{label}</span><input className="input-field" placeholder="Document number, date, approving office, storage location" value={settings.compliance[key] || ''} onChange={(e) => setSettings((current) => ({ ...current, compliance: { ...current.compliance, [key]: e.target.value } }))} /></label>)}</div><div className="modal-actions"><button className="btn-primary" onClick={saveCompliance}><Save size={16} /> Save evidence register</button></div></section>
    <section className="card-static"><h2>Retention and deletion procedure</h2><ol className="numbered-list"><li>Enrollment frames: retain encrypted only as long as documented as necessary for model retraining; define the maximum staging period in the approved schedule.</li><li>LBPH samples/model: retain while the person remains enrolled/employed and the lawful attendance purpose continues; retrain after authorized removal.</li><li>Attendance, SF2, and grades: retain under the approved DepEd/National Archives records-disposition schedule—not an invented universal period.</li><li>SMS operational logs: keep only long enough to reconcile delivery and complaints, then purge under the approved schedule.</li><li>Before deletion, the records officer checks legal holds/disputes, obtains disposal authority, erases active copies/backups as they cycle out, and retains a non-content destruction certificate.</li></ol><h3>Privacy principles</h3><div className="principle-grid"><div><strong>Transparency</strong><span>Gate notice, complete privacy notice, DPO contact, explain matching and correction.</span></div><div><strong>Legitimate purpose</strong><span>Attendance, safety notice, grading, and required reports only.</span></div><div><strong>Proportionality</strong><span>Minimum data, local processing, one-person lane, no emotion/profiling use.</span></div><div><strong>Safeguards</strong><span>Access controls, encryption, audit, physical protection, response and disposal.</span></div></div></section>
  </div>;
}

function AccessControls() {
  const rows = [
    ['Administrator', 'Accounts, persons, enrollment/training, rules, reports, SMS, corrections, audit', 'Cannot silently overwrite/delete raw gate events'],
    ['Teacher/adviser', 'Assigned attendance review/correction, schedules, grading, class reports', 'No biometric source files or gateway secrets'],
    ['Scanner device', 'Live camera recognition and gate event display', 'No roster editing, reports, grades, corrections, or secrets'],
    ['Guard/security staff', 'Physically secure the gate laptop and report incidents; use only the scanner device session', 'No independent student-record access'],
    ['Records officer / DPO', 'Records validation or privacy oversight through individually assigned accounts in production', 'No routine use beyond official function'],
  ];
  return <div className="page-stack"><section className="card-static"><div className="section-heading"><div><p className="eyebrow">Least privilege</p><h2>Role-based access</h2></div><UsersRound size={25} /></div><div className="table-scroll"><table className="interactive-table"><thead><tr><th>Role</th><th>Authorized capability</th><th>Restriction</th></tr></thead><tbody>{rows.map((row) => <tr key={row[0]}><td><strong>{row[0]}</strong></td><td>{row[1]}</td><td>{row[2]}</td></tr>)}</tbody></table></div></section><section className="card-static"><h2>Attendance correction procedure</h2><ol className="numbered-list"><li>Teacher/admin compares the displayed result with the immutable gate event and supporting evidence.</li><li>Select corrected status/time and enter a specific reason; the system records actor, role, timestamp, old value, new value, and reason.</li><li>For disputed learner records, the adviser verifies the request and the records officer withholds final SF2 submission until resolved.</li><li>The records officer validates monthly totals and male/female placement before approving the generated workbook.</li><li>The DPO handles privacy-rights requests and suspected unauthorized changes under the incident procedure.</li></ol></section><section className="card-static source-card"><h3>Primary references to validate with the DPO/SDO</h3><div className="source-links"><a href="https://www.deped.gov.ph/wp-content/uploads/DO_s2026_003r-1.pdf" target="_blank" rel="noreferrer">DepEd Order No. 003, s. 2026 <ExternalLink size={14} /></a><a href="https://privacy.gov.ph/data-privacy-act/" target="_blank" rel="noreferrer">Data Privacy Act <ExternalLink size={14} /></a><a href="https://github.com/capcom6/android-sms-gateway" target="_blank" rel="noreferrer">Android SMS Gateway <ExternalLink size={14} /></a></div></section></div>;
}
