import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, ArchiveRestore, CheckCircle2, Database, Download, FileUp, KeyRound, Pencil, Plus, Save, ShieldAlert, Trash2, UserCog, Users } from 'lucide-react';
import { api, auth } from '../../api/client';

const tabs = [['people', 'People & records'], ['accounts', 'Accounts'], ['academic', 'Academic structure'], ['roster', 'Roster import'], ['recovery', 'Backup & recovery']];
const emptyPerson = { external_id: '', lrn: '', full_name: '', sex: 'Female', role: 'Student', grade: '', section: '', assignment: '', guardian_phone: '', biometric_consent: false };
const emptyUser = { username: '', password: '', role: 'teacher', full_name: '', active: true };

export default function Administration() {
  const [active, setActive] = useState('people');
  const [people, setPeople] = useState([]);
  const [users, setUsers] = useState([]);
  const [structure, setStructure] = useState({ school_years: [], grading_periods: [], grade_levels: [], sections: [], subjects: [] });
  const [imports, setImports] = useState([]);
  const [disposals, setDisposals] = useState([]);
  const [backups, setBackups] = useState([]);
  const [notice, setNotice] = useState('');
  const [error, setError] = useState('');

  const load = useCallback(async () => {
    try {
      const [personRows, accountRows, academicRows, importRows, disposalRows, backupRows] = await Promise.all([
        api.get('/admin/persons'), api.get('/admin/users'), api.get('/admin/academic-structure'),
        api.get('/admin/roster/imports'), api.get('/admin/disposals'), api.get('/admin/backups'),
      ]);
      setPeople(personRows); setUsers(accountRows); setStructure(academicRows);
      setImports(importRows); setDisposals(disposalRows); setBackups(backupRows);
    } catch (err) { setError(err.message); }
  }, []);

  useEffect(() => { load(); }, [load]);
  const success = (message) => { setNotice(message); setError(''); window.setTimeout(() => setNotice(''), 4000); };
  const fail = (err) => { setError(err.message); setNotice(''); };

  return <div className="page-stack">
    <div className="page-heading"><div><p className="eyebrow">Authorized administration</p><h1>School data administration</h1><p>Maintain school records, user accounts, academic references, approved roster imports, and encrypted recovery packages.</p></div><Database size={34} /></div>
    {notice && <div className="notice notice-success"><CheckCircle2 size={18} /> {notice}</div>}
    {error && <div className="notice notice-danger"><AlertTriangle size={18} /> {error}</div>}
    <div className="setup-tabs">{tabs.map(([id, label]) => <button key={id} className={active === id ? 'active' : ''} onClick={() => setActive(id)}>{label}</button>)}</div>
    {active === 'people' && <PeopleManager people={people} disposals={disposals} reload={load} success={success} fail={fail} />}
    {active === 'accounts' && <AccountManager users={users} reload={load} success={success} fail={fail} />}
    {active === 'academic' && <AcademicManager structure={structure} reload={load} success={success} fail={fail} />}
    {active === 'roster' && <RosterManager imports={imports} reload={load} success={success} fail={fail} />}
    {active === 'recovery' && <RecoveryManager backups={backups} reload={load} success={success} fail={fail} />}
  </div>;
}

function PeopleManager({ people, disposals, reload, success, fail }) {
  const [form, setForm] = useState(emptyPerson);
  const [editing, setEditing] = useState(null);
  const [disposal, setDisposal] = useState(null);
  const patch = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  const edit = (item) => { setEditing(item.id); setForm(Object.fromEntries(Object.keys(emptyPerson).map((key) => [key, item[key] ?? emptyPerson[key]]))); };
  const save = async (event) => {
    event.preventDefault();
    try {
      const payload = { ...form, lrn: form.lrn || null, grade: form.grade || null, section: form.section || null, assignment: form.assignment || null, guardian_phone: form.guardian_phone || null };
      if (editing) await api.patch(`/persons/${editing}`, payload); else await api.post('/persons', payload);
      success(editing ? 'School record updated.' : 'School record created.'); setEditing(null); setForm(emptyPerson); await reload();
    } catch (err) { fail(err); }
  };
  const setActive = async (item) => { const data = new FormData(); data.append('active', String(!item.active)); try { await api.post(`/admin/persons/${item.id}/active`, data); success(`${item.full_name} ${item.active ? 'deactivated' : 'reactivated'}.`); await reload(); } catch (err) { fail(err); } };
  return <div className="page-stack">
    <section className="card-static"><div className="section-heading"><div><p className="eyebrow">Students, faculty, and personnel</p><h2>{editing ? 'Edit school record' : 'Add school record'}</h2></div><Users size={24} /></div>
      <form onSubmit={save}><div className="form-grid three-columns">
        <Field label="School / employee ID" value={form.external_id} onChange={(value) => patch('external_id', value)} required />
        <Field label="LRN (students)" value={form.lrn} onChange={(value) => patch('lrn', value)} />
        <Field label="Full name" value={form.full_name} onChange={(value) => patch('full_name', value)} required />
        <SelectField label="Sex for SF2" value={form.sex} onChange={(value) => patch('sex', value)} options={['Female', 'Male']} />
        <SelectField label="Role" value={form.role} onChange={(value) => patch('role', value)} options={['Student', 'Faculty', 'Non-teaching Personnel']} />
        <Field label="Guardian phone" value={form.guardian_phone} onChange={(value) => patch('guardian_phone', value)} />
        <Field label="Grade level" value={form.grade} onChange={(value) => patch('grade', value)} required={form.role === 'Student'} />
        <Field label="Section" value={form.section} onChange={(value) => patch('section', value)} required={form.role === 'Student'} />
        <Field label="Office / assignment" value={form.assignment} onChange={(value) => patch('assignment', value)} />
        <label className="checkbox-field"><input type="checkbox" checked={form.biometric_consent} onChange={(event) => patch('biometric_consent', event.target.checked)} /><span>Authorized biometric enrollment consent is documented</span></label>
      </div><div className="modal-actions">{editing && <button type="button" className="btn-secondary" onClick={() => { setEditing(null); setForm(emptyPerson); }}>Cancel</button>}<button className="btn-primary"><Save size={16} /> {editing ? 'Save changes' : 'Create record'}</button></div></form>
    </section>
    <section className="card-static"><h2>School records</h2><p className="section-copy">Deactivation preserves history. Full disposal is a separate, authorized action that deletes linked attendance, grades, SMS, interventions, and biometric data while retaining a non-identifying disposal audit.</p><div className="table-scroll"><table className="interactive-table"><thead><tr><th>Name</th><th>ID / LRN</th><th>Role / placement</th><th>Face samples</th><th>Status</th><th /></tr></thead><tbody>{people.map((item) => <tr key={item.id}><td><strong>{item.full_name}</strong></td><td>{item.external_id}<span className="table-subline">{item.lrn || 'No LRN'}</span></td><td>{item.role}<span className="table-subline">{item.grade ? `Grade ${item.grade} — ${item.section}` : item.assignment || '—'}</span></td><td>{item.sample_count}</td><td><span className={`tag ${item.active ? 'tag-success' : 'tag-gray'}`}>{item.active ? 'Active' : 'Inactive'}</span></td><td><div className="table-actions"><button className="btn-link" onClick={() => edit(item)}><Pencil size={14} /> Edit</button><button className="btn-link" onClick={() => setActive(item)}>{item.active ? 'Deactivate' : 'Reactivate'}</button><button className="btn-link danger-link" onClick={() => setDisposal(item)}><Trash2 size={14} /> Full disposal</button></div></td></tr>)}</tbody></table></div></section>
    <section className="card-static"><h2>Record-disposal audit</h2><div className="table-scroll"><table className="interactive-table"><thead><tr><th>Completed</th><th>Anonymous reference</th><th>Authority</th><th>Reason</th><th>Removed</th><th>Actor</th></tr></thead><tbody>{disposals.length === 0 && <tr><td colSpan="6" className="empty-cell">No full record disposal has been performed.</td></tr>}{disposals.map((item) => <tr key={item.id}><td>{new Date(item.created_at).toLocaleString('en-PH')}</td><td>{item.disposal_reference}</td><td>{item.authorization_reference}</td><td>{item.reason}</td><td>{Object.entries(item.removed_counts).map(([key, value]) => `${key}: ${value}`).join(', ')}</td><td>{item.actor_name}</td></tr>)}</tbody></table></div></section>
    {disposal && <DisposalModal person={disposal} onClose={() => setDisposal(null)} onDone={async () => { setDisposal(null); success('The selected person and all linked school records were securely disposed.'); await reload(); }} fail={fail} />}
  </div>;
}

function DisposalModal({ person, onClose, onDone, fail }) {
  const [reason, setReason] = useState(''); const [reference, setReference] = useState(''); const [confirmation, setConfirmation] = useState('');
  const submit = async (event) => { event.preventDefault(); try { await api.delete(`/admin/persons/${person.id}/records`, { reason, authorization_reference: reference, confirmation }); await onDone(); } catch (err) { fail(err); } };
  return <div className="modal-backdrop"><form className="modal-card" onSubmit={submit}><div className="modal-header"><div><p className="eyebrow">Irreversible authorized disposal</p><h2>Delete all records for {person.full_name}</h2></div><ShieldAlert color="#dc2626" /></div><div className="notice notice-danger">This removes the identity record plus linked face samples/model membership, gate events, corrections, grades, SMS, excuses, and intervention records. Export or back up first when the approved retention schedule requires it.</div><div className="form-grid"><Field label="Documented reason" value={reason} onChange={setReason} required /><Field label="Authorization / disposition reference" value={reference} onChange={setReference} required /><Field label={`Type the school ID ${person.external_id}`} value={confirmation} onChange={setConfirmation} required /></div><div className="modal-actions"><button type="button" className="btn-secondary" onClick={onClose}>Cancel</button><button className="btn-danger"><Trash2 size={16} /> Permanently dispose records</button></div></form></div>;
}

function AccountManager({ users, reload, success, fail }) {
  const [form, setForm] = useState(emptyUser); const [editing, setEditing] = useState(null);
  const [passwords, setPasswords] = useState({ current_password: '', new_password: '' });
  const patch = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  const edit = (item) => { setEditing(item.id); setForm({ username: item.username, password: '', role: item.role, full_name: item.full_name, active: item.active }); };
  const save = async (event) => { event.preventDefault(); try { if (editing) await api.put(`/admin/users/${editing}`, { role: form.role, full_name: form.full_name, active: form.active, new_password: form.password || null }); else await api.post('/admin/users', form); success(editing ? 'Account updated.' : 'Account created.'); setEditing(null); setForm(emptyUser); await reload(); } catch (err) { fail(err); } };
  const deactivate = async (item) => { try { await api.delete(`/admin/users/${item.id}`); success(`${item.username} was deactivated.`); await reload(); } catch (err) { fail(err); } };
  const changePassword = async (event) => { event.preventDefault(); try { await api.post('/auth/change-password', passwords); setPasswords({ current_password: '', new_password: '' }); success('Your password was changed.'); } catch (err) { fail(err); } };
  return <div className="page-stack"><section className="card-static"><div className="section-heading"><div><p className="eyebrow">Role-based access</p><h2>{editing ? 'Edit account' : 'Create account'}</h2></div><UserCog size={24} /></div><form onSubmit={save}><div className="form-grid three-columns"><Field label="Username" value={form.username} onChange={(value) => patch('username', value)} disabled={Boolean(editing)} required /><Field label={editing ? 'New password (optional)' : 'Temporary password'} type="password" value={form.password} onChange={(value) => patch('password', value)} required={!editing} /><Field label="Full name" value={form.full_name} onChange={(value) => patch('full_name', value)} required /><SelectField label="Role" value={form.role} onChange={(value) => patch('role', value)} options={['admin', 'teacher', 'scanner']} /><label className="checkbox-field"><input type="checkbox" checked={form.active} onChange={(event) => patch('active', event.target.checked)} /><span>Account is active</span></label></div><div className="modal-actions">{editing && <button type="button" className="btn-secondary" onClick={() => { setEditing(null); setForm(emptyUser); }}>Cancel</button>}<button className="btn-primary"><Save size={16} /> Save account</button></div></form><div className="table-scroll"><table className="interactive-table"><thead><tr><th>Name</th><th>Username</th><th>Role</th><th>Status</th><th /></tr></thead><tbody>{users.map((item) => <tr key={item.id}><td>{item.full_name}</td><td>{item.username}</td><td>{item.role}</td><td>{item.active ? 'Active' : 'Inactive'}</td><td><div className="table-actions"><button className="btn-link" onClick={() => edit(item)}><Pencil size={14} /> Edit</button>{item.active && item.username !== 'admin' && <button className="btn-link danger-link" onClick={() => deactivate(item)}>Deactivate</button>}</div></td></tr>)}</tbody></table></div></section>
    <section className="card-static"><div className="section-heading"><div><p className="eyebrow">Signed in as {auth.name()}</p><h2>Change my password</h2></div><KeyRound size={24} /></div><form onSubmit={changePassword}><div className="form-grid two-columns"><Field label="Current password" type="password" value={passwords.current_password} onChange={(value) => setPasswords((current) => ({ ...current, current_password: value }))} required /><Field label="New password (at least 10 characters)" type="password" value={passwords.new_password} onChange={(value) => setPasswords((current) => ({ ...current, new_password: value }))} required /></div><div className="modal-actions"><button className="btn-primary"><KeyRound size={16} /> Change password</button></div></form></section></div>;
}

function AcademicManager({ structure, reload, success, fail }) {
  const firstYear = structure.school_years[0]?.id || '';
  const firstGrade = structure.grade_levels[0]?.id || '';
  const [year, setYear] = useState({ id: null, name: '', starts_on: '', ends_on: '', active: true });
  const [period, setPeriod] = useState({ id: null, school_year_id: '', name: 'Quarter 1', quarter: 1, starts_on: '', ends_on: '', active: true });
  const [grade, setGrade] = useState({ id: null, name: '', sequence: 0, active: true });
  const [section, setSection] = useState({ id: null, grade_level_id: '', name: '', adviser_name: '', active: true });
  const [subject, setSubject] = useState({ id: null, code: '', name: '', active: true });
  useEffect(() => { if (!period.school_year_id && firstYear) setPeriod((current) => ({ ...current, school_year_id: firstYear })); if (!section.grade_level_id && firstGrade) setSection((current) => ({ ...current, grade_level_id: firstGrade })); }, [firstYear, firstGrade, period.school_year_id, section.grade_level_id]);
  const save = async (path, value, reset, label) => { try { await api.post(`/admin/${path}`, value); reset(); success(`${label} saved.`); await reload(); } catch (err) { fail(err); } };
  const remove = async (kind, id) => { try { await api.delete(`/admin/reference/${kind}/${id}`); success('Reference record deleted.'); await reload(); } catch (err) { fail(err); } };
  return <div className="page-stack"><div className="notice notice-blue"><Database size={18} /> These records organize gradebooks by school year, quarter, subject, grade level, and section. In-use references should be deactivated rather than deleted.</div>
    <ReferenceCard title="School years" rows={structure.school_years} columns={['name', 'starts_on', 'ends_on']} onEdit={setYear} onDelete={(id) => remove('school-years', id)}><div className="form-grid three-columns"><Field label="Name" value={year.name} onChange={(value) => setYear({ ...year, name: value })} /><Field label="Starts" type="date" value={year.starts_on} onChange={(value) => setYear({ ...year, starts_on: value })} /><Field label="Ends" type="date" value={year.ends_on} onChange={(value) => setYear({ ...year, ends_on: value })} /></div><SaveReference onClick={() => save('school-years', year, () => setYear({ id: null, name: '', starts_on: '', ends_on: '', active: true }), 'School year')} /></ReferenceCard>
    <ReferenceCard title="Grading periods" rows={structure.grading_periods} columns={['school_year', 'name', 'quarter', 'starts_on', 'ends_on']} onEdit={(item) => setPeriod({ ...item })} onDelete={(id) => remove('grading-periods', id)}><div className="form-grid three-columns"><label><span className="field-label">School year</span><select className="input-field" value={period.school_year_id} onChange={(event) => setPeriod({ ...period, school_year_id: Number(event.target.value) })}>{structure.school_years.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><Field label="Name" value={period.name} onChange={(value) => setPeriod({ ...period, name: value })} /><Field label="Quarter" type="number" value={period.quarter} onChange={(value) => setPeriod({ ...period, quarter: Number(value) })} /><Field label="Starts" type="date" value={period.starts_on} onChange={(value) => setPeriod({ ...period, starts_on: value })} /><Field label="Ends" type="date" value={period.ends_on} onChange={(value) => setPeriod({ ...period, ends_on: value })} /></div><SaveReference onClick={() => save('grading-periods', period, () => setPeriod({ id: null, school_year_id: firstYear, name: 'Quarter 1', quarter: 1, starts_on: '', ends_on: '', active: true }), 'Grading period')} /></ReferenceCard>
    <ReferenceCard title="Grade levels" rows={structure.grade_levels} columns={['name', 'sequence', 'active']} onEdit={setGrade} onDelete={(id) => remove('grade-levels', id)}><div className="form-grid two-columns"><Field label="Grade level" value={grade.name} onChange={(value) => setGrade({ ...grade, name: value })} /><Field label="Sort sequence" type="number" value={grade.sequence} onChange={(value) => setGrade({ ...grade, sequence: Number(value) })} /></div><SaveReference onClick={() => save('grade-levels', grade, () => setGrade({ id: null, name: '', sequence: 0, active: true }), 'Grade level')} /></ReferenceCard>
    <ReferenceCard title="Sections" rows={structure.sections} columns={['grade', 'name', 'adviser_name', 'active']} onEdit={(item) => setSection({ ...item })} onDelete={(id) => remove('sections', id)}><div className="form-grid three-columns"><label><span className="field-label">Grade level</span><select className="input-field" value={section.grade_level_id} onChange={(event) => setSection({ ...section, grade_level_id: Number(event.target.value) })}>{structure.grade_levels.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><Field label="Section" value={section.name} onChange={(value) => setSection({ ...section, name: value })} /><Field label="Adviser" value={section.adviser_name || ''} onChange={(value) => setSection({ ...section, adviser_name: value || null })} /></div><SaveReference onClick={() => save('sections', section, () => setSection({ id: null, grade_level_id: firstGrade, name: '', adviser_name: '', active: true }), 'Section')} /></ReferenceCard>
    <ReferenceCard title="Subjects" rows={structure.subjects} columns={['code', 'name', 'active']} onEdit={setSubject} onDelete={(id) => remove('subjects', id)}><div className="form-grid two-columns"><Field label="Subject code" value={subject.code} onChange={(value) => setSubject({ ...subject, code: value })} /><Field label="Subject name" value={subject.name} onChange={(value) => setSubject({ ...subject, name: value })} /></div><SaveReference onClick={() => save('subjects', subject, () => setSubject({ id: null, code: '', name: '', active: true }), 'Subject')} /></ReferenceCard>
  </div>;
}

function ReferenceCard({ title, rows, columns, onEdit, onDelete, children }) { return <section className="card-static"><h2>{title}</h2>{children}<div className="table-scroll"><table className="interactive-table"><thead><tr>{columns.map((column) => <th key={column}>{column.replaceAll('_', ' ')}</th>)}<th /></tr></thead><tbody>{rows.map((item) => <tr key={item.id}>{columns.map((column) => <td key={column}>{String(item[column] ?? '—')}</td>)}<td><div className="table-actions"><button className="btn-link" onClick={() => onEdit(item)}><Pencil size={14} /> Edit</button><button className="btn-link danger-link" onClick={() => onDelete(item.id)}><Trash2 size={14} /> Delete</button></div></td></tr>)}</tbody></table></div></section>; }
function SaveReference({ onClick }) { return <div className="modal-actions"><button type="button" className="btn-primary" onClick={onClick}><Save size={16} /> Save reference</button></div>; }

function RosterManager({ imports, reload, success, fail }) {
  const [file, setFile] = useState(null); const [reference, setReference] = useState(''); const [preview, setPreview] = useState(null);
  const run = async (dryRun) => { if (!file) return fail(new Error('Select an approved .xlsx roster.')); const form = new FormData(); form.append('file', file); form.append('approved_reference', reference); form.append('dry_run', String(dryRun)); try { const result = await api.post('/admin/roster/import', form); setPreview(result); if (!dryRun) { success(`Roster imported: ${result.inserted} inserted and ${result.updated} updated.`); await reload(); } } catch (err) { fail(err); } };
  return <div className="page-stack"><section className="card-static"><div className="section-heading"><div><p className="eyebrow">Approved spreadsheet workflow</p><h2>Bulk roster import</h2></div><FileUp size={26} /></div><p className="section-copy">Required columns: External ID, Full Name, Sex, and Role. Students also require Grade and Section. Optional columns are LRN, Assignment, and Guardian Phone. Existing records with the same ID or LRN are updated.</p><div className="form-grid two-columns"><label><span className="field-label">Approved .xlsx roster</span><input className="input-field" type="file" accept=".xlsx" onChange={(event) => { setFile(event.target.files?.[0] || null); setPreview(null); }} /></label><Field label="School approval / source reference" value={reference} onChange={setReference} required /></div><div className="modal-actions"><button className="btn-secondary" onClick={() => run(true)}><FileUp size={16} /> Validate preview</button><button className="btn-primary" disabled={!preview?.dry_run || preview.invalid_rows > 0} onClick={() => run(false)}><Plus size={16} /> Import valid roster</button></div>{preview && <div className={`notice ${preview.invalid_rows ? 'notice-danger' : 'notice-success'}`}>Valid rows: {preview.valid_rows ?? preview.inserted + preview.updated}. Invalid rows: {preview.invalid_rows}. {preview.errors?.slice(0, 8).map((item) => `Row ${item.row}: ${item.errors.join(', ')}`).join(' · ')}</div>}</section>
    <section className="card-static"><h2>Roster import audit</h2><div className="table-scroll"><table className="interactive-table"><thead><tr><th>Imported</th><th>File</th><th>Approval</th><th>Counts</th><th>Actor</th><th>SHA-256</th></tr></thead><tbody>{imports.length === 0 && <tr><td colSpan="6" className="empty-cell">No approved roster has been imported.</td></tr>}{imports.map((item) => <tr key={item.id}><td>{new Date(item.created_at).toLocaleString('en-PH')}</td><td>{item.filename}</td><td>{item.approved_reference}</td><td>{item.inserted_count} added, {item.updated_count} updated</td><td>{item.actor_name}</td><td className="model-version">{item.file_sha256}</td></tr>)}</tbody></table></div></section></div>;
}

function RecoveryManager({ backups, reload, success, fail }) {
  const [passphrase, setPassphrase] = useState(''); const [restoreFile, setRestoreFile] = useState(null); const [restorePassphrase, setRestorePassphrase] = useState(''); const [confirmation, setConfirmation] = useState('');
  const create = async () => { const form = new FormData(); form.append('passphrase', passphrase); try { const result = await api.post('/admin/backups', form); setPassphrase(''); success(`Encrypted backup ${result.filename} created.`); await reload(); } catch (err) { fail(err); } };
  const restore = async () => { if (!restoreFile) return fail(new Error('Select an .edubak recovery file.')); const form = new FormData(); form.append('file', restoreFile); form.append('passphrase', restorePassphrase); form.append('confirmation', confirmation); try { const result = await api.post('/admin/backups/restore', form); setRestorePassphrase(''); setConfirmation(''); success(`Backup integrity verified (${result.file_count} files). Restart EduScan to apply the staged restore.`); } catch (err) { fail(err); } };
  return <div className="page-stack"><section className="card-static"><div className="section-heading"><div><p className="eyebrow">SQLite, encryption key, faces, models, templates</p><h2>Create encrypted backup</h2></div><Database size={25} /></div><div className="notice notice-warning"><KeyRound size={18} /> The passphrase is not stored. Keep it in the school’s approved password vault and retain an off-device copy of the .edubak file.</div><div className="form-grid two-columns"><Field label="Backup passphrase (at least 12 characters)" type="password" value={passphrase} onChange={setPassphrase} /><div className="modal-actions"><button className="btn-primary" onClick={create}><Database size={16} /> Create secure backup</button></div></div><div className="table-scroll"><table className="interactive-table"><thead><tr><th>Created</th><th>Filename</th><th>Size</th><th /></tr></thead><tbody>{backups.length === 0 && <tr><td colSpan="4" className="empty-cell">No secure backup has been created.</td></tr>}{backups.map((item) => <tr key={item.filename}><td>{new Date(item.created_at).toLocaleString('en-PH')}</td><td>{item.filename}</td><td>{(item.size_bytes / 1024 / 1024).toFixed(2)} MB</td><td><button className="btn-link" onClick={() => api.download(`/admin/backups/${encodeURIComponent(item.filename)}`, item.filename).catch(fail)}><Download size={15} /> Download</button></td></tr>)}</tbody></table></div></section>
    <section className="card-static"><div className="section-heading"><div><p className="eyebrow">Controlled two-stage recovery</p><h2>Verify and stage a restore</h2></div><ArchiveRestore size={25} /></div><p className="section-copy">The server decrypts and verifies every file hash first. It applies the staged database and matching encryption key only at the next restart, while preserving the current data in a timestamped pre-restore recovery folder.</p><div className="form-grid three-columns"><label><span className="field-label">EduScan .edubak file</span><input className="input-field" type="file" accept=".edubak" onChange={(event) => setRestoreFile(event.target.files?.[0] || null)} /></label><Field label="Backup passphrase" type="password" value={restorePassphrase} onChange={setRestorePassphrase} /><Field label="Type STAGE RESTORE" value={confirmation} onChange={setConfirmation} /></div><div className="modal-actions"><button className="btn-danger" onClick={restore}><ArchiveRestore size={16} /> Verify and stage restore</button></div></section></div>;
}

function Field({ label, value, onChange, type = 'text', required = false, disabled = false }) { return <label><span className="field-label">{label}</span><input className="input-field" type={type} value={value ?? ''} onChange={(event) => onChange(event.target.value)} required={required} disabled={disabled} /></label>; }
function SelectField({ label, value, onChange, options }) { return <label><span className="field-label">{label}</span><select className="input-field" value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
